### ISSUE TITLE
Incorrect australian time-zones

### ISSUE THREAD

**Issue by OmgImAlexis** [filipdanic/compact-timezone-list#2]
I have a feeling you've used the daylight savings "time-zones" for the last few as they seem to be ahead by 1 hour.

```
  { offset: '+08:00', label: '(GMT+08:00) Western Time - Perth', tzCode: 'Australia/Perth' },
  { offset: '+09:30', label: '(GMT+09:30) Central Time - Darwin', tzCode: 'Australia/Darwin' },
  { offset: '+10:00', label: '(GMT+10:00) Eastern Time - Brisbane', tzCode: 'Australia/Brisbane' },
  { offset: '+10:30', label: '(GMT+10:30) Central Time - Adelaide', tzCode: 'Australia/Adelaide' },
  { offset: '+11:00', label: '(GMT+11:00) Eastern Time - Hobart', tzCode: 'Australia/Hobart' },
  { offset: '+11:00', label: '(GMT+11:00) Eastern Time - Melbourne, Sydney', tzCode: 'Australia/Sydney' },
```

```
(UTC +10) - Brisbane, Sydney, Melbourne, Hobart, Canberra
(UTC +9.5) - Adelaide, Darwin, Broken Hill
(UTC +8) - Perth
```

Ref: https://www.australia.gov.au/about-australia/facts-and-figures/time-zones-and-daylight-saving

**Comment by filipdanic** [comment]
Hey there, thanks for opening the issue!

I didn’t really include all of these manually, they come from the `tz` dataset. I feel they should be pretty accurate. The discrepancy you’ve pointed out is, apparently, due to this:

>  The UTC DST offset is different from the UTC offset for zones where daylight saving time is observed.

So, while it’s true that `Australia/Adelaide` has a UTC (GMT) offset of `+09:30`, the UTC DST offset would be `+10:30`. For my own use case, this doesn’t really matter. I’d use other other libraries and the `tzCode` for any serious calculations.

Maybe we could rename the `offset` key into `utcOffset` and add the UTC DST info in there as well. If this is something you could do, please let me know. :D

**Comment by vdh** [comment]
It's a bad idea to bake the offset into the label string, because for the half of the year in all the regions using DST that label is going to be inaccurate.

**Comment by vvo** [comment]
@vdh I had this exact same conclusion while building my own time zones list, it only embeds the "non DST/summmer time) offsets but allows you to programmatically get the "current time" offsets.

I would be happy getting your feedback here: https://github.com/vvo/tzdb/
